import { ReactNode } from 'react';
import Navbar from './component/navbar';
import Providers from './component/providers';
import './global.css';
import Footer from './component/footer';

export const metadata = {
  title: 'Welcome to book-library',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="w-full">
            <Navbar />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
